php artisan config:clear
php artisan cache:clear
php artisan route:clear
php artisan view:clear
php artisan clear-compiled
php artisan event:clear
php artisan optimize:clear
php artisan optimize
php artisan view:cache
